# ===========================================
# Site Information Settings
# ===========================================

# Site creation time
since: 2023

# Custom your favicon.ico in `site/source`
favicon: /favicon.ico

# Set feed link (false | default | your feed link)
# false: disable
# default: use `atom.xml`, generator for `hexo-generator-feed`
rss: default

language: en

# ===========================================
# Menu Settings
# ===========================================
menu:
  Home: /
  Archive: /archives
  About: /about

# ===========================================
# Widget Settings
# ===========================================
# widget function
# false: disable
# widget_custom: custom your widget
#   title: your widget title
#   content: Add your html code in here. Example: <p>Hello, I am Frost</p>
widget:
  Tags: true
  Categories: true

# widget_custom:
#     title:
#     content:

# ===========================================
# Theme Settings
# ===========================================
# theme styling
# color: Default | Mint Green | Cobalt Blue | Hot Pink | Dark Violet
theme:
  color: Default
  fancybox: false

# ===========================================
# Third Party Services Settings
# ===========================================

# Baidu Analytics
baidu_analytics:
# Google Analytics
google_analytics:

# Duoshuo
duoshuo_shortname:
# Disqus
disqus_shortname:
# utterances
utterances:
  enable: true
  repo: meannoharm/meannoharm.github.io
  issueTerm: pathname
  theme: github-light


# ===========================================
# Version
# ===========================================
version: 1.1

# ===========================================
# Footer Settings
# ===========================================
license:
  name: CC-BY-NC-SA 4.0
  link: https://creativecommons.org/licenses/by-nc-sa/4.0/
